
<% 
' ---- These constants are used by the UserFlags property

Const UF_SCRIPT                    = &H0001
Const UF_ACCOUNTDISABLE            = &H0002
Const UF_HOMEDIR_REQUIRED          = &H0008
Const UF_LOCKOUT                   = &H0010
Const UF_PASSWD_NOTREQD            = &H0020
Const UF_PASSWD_CANT_CHANGE        = &H0040
Const UF_TEMP_DUPLICATE_ACCOUNT    = &H0100
Const UF_NORMAL_ACCOUNT            = &H0200
Const UF_INTERDOMAIN_TRUST_ACCOUNT = &H0800
Const UF_WORKSTATION_TRUST_ACCOUNT = &H1000
Const UF_SERVER_TRUST_ACCOUNT      = &H2000
Const UF_DONT_EXPIRE_PASSWD        = &H10000  
Const UF_MNS_LOGON_ACCOUNT         = &H20000
%>