<%
title = "Website Builder Features"
description = "Create an ecommerce store with our easy to use point and click interface.	 No special knowledge or tools required, free packages available."
keyword1="website builder"
keyword2="accept credit cards online"
keyword3="store creator"
keyword4="free templates"
keyword5=""

include_extra_links = false
include_credit = false
tracking_page_name="features"

%>
<SCRIPT LANGUAGE="JavaScript">
	function goShowFeature(resCtrl) {
		var w = 450
		var h = 400
		var winl = (screen.width - w) / 2;
		var wint = (screen.height - h) / 2;
		winprops = 'height='+h+',width='+w+',top='+wint+',left='+winl
		theUrl='include/'+resCtrl+'.asp';
		reWin = window.open(theUrl,'Features','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,'+winprops);}

</script>

<!--#include file="header.asp"-->
<table width=525 align=left border=1 cellspacing=0 cellpadding=3>
<tr bgcolor=DDDDDD><td width="50%"><B>Store Setup</b></td><td width="10%" align=center><B>BASIC</b></td><td width="10%" align=center><B>BRONZE</b></td><td width="10%" align=center><B>SILVER</b></td><td width="10%" align=center><B>GOLD</b></td><td width="10%" align=center><B>PLAT</b></td><td width="10%" align=center><B>UNLIM</b></td></tr>
<tr><td>Free Setup</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Free Hosting</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Store Building Wizard</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Flexible Taxes</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Flexible Shipping Methods</td><td align=center><img src=images/checkbox.gif border=0><td align=center><img src=images/checkbox.gif border=0></td></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Accepted Payment Methods<td align=center><img src=images/checkbox.gif border=0></td></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Merchant Email Order Notification</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Automatic Customer Receipts</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Online Customer Order Tracking</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Separate Bill To/Ship To addresses</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Customer Search</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Members Only or Public Store</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Offer Gift Wrapping</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Ability to Close Store</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Realtime Shipping (UPS, USPS, DHL, FedEx)</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Export Order to Text File</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Import Products from Text File</td><td align=center>&nbsp;</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Export Customers to Text File</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Quickbooks Integration</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>

<tr bgcolor=DDDDDD><td width="50%"><B>Inventory</b></td><td width="10%" align=center><B>BASIC</b></td><td width="10%" align=center><B>BRONZE</b></td><td width="10%" align=center><B>SILVER</b></td><td width="10%" align=center><B>GOLD</b></td><td width="10%" align=center><B>PLAT</b></td><td width="10%" align=center><B>UNLIM</b></td></tr>
<tr><td>Maximum Departments / Subdepartments</b></td><td align=center>1</td><td align=center>2</td><td align=center>5</td><td align=center>25</td><td align=center>50</td><td align=center>Unlim</td></tr>
<tr><td>Maximum Products</td><td align=center>10</td><td align=center>20</td><td align=center>50</td><td align=center>250</td><td align=center>500</td><td align=center>Unlim</td></tr>
<tr><td>Detailed and Overview Product Pages</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Product Custom Fields</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Product Options (size, color, etc)</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Inventory Control</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Automatic Inventory Quantity Update</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Minimum Sell Quantity</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Mass Edit</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Quick Edit</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Automatic Software Product Download</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>


<tr bgcolor=DDDDDD><td width="50%"><B>Store Design</b></td><td width="10%" align=center><B>BASIC</b></td><td width="10%" align=center><B>BRONZE</b></td><td width="10%" align=center><B>SILVER</b></td><td width="10%" align=center><B>GOLD</b></td><td width="10%" align=center><B>PLAT</b></td><td width="10%" align=center><B>UNLIM</b></td></tr>
<tr><td>Custom Image Upload</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>WYSIWYG Editor</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Simple Logo Creation</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Dozens of Custom Templates</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Customize Each Page</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Build a custom template</td><td>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Customizable Catalog Pages</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Add Custom Pages</td><td align=center>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Powered by Link</td><td align=center><img src=images/checkbox.gif border=0></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>

<tr bgcolor=DDDDDD><td width="50%"><B>Other Features</b></td><td width="10%" align=center><B>BASIC</b></td><td width="10%" align=center><B>BRONZE</b></td><td width="10%" align=center><B>SILVER</b></td><td width="10%" align=center><B>GOLD</b></td><td width="10%" align=center><B>PLAT</b></td><td width="10%" align=center><B>UNLIM</b></td></tr>
<tr><td>Securely Accept Credit Cards</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Process CC Automatically</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Integrated with Authorize.Net, PlugnPay, Internet Secure, 
Linkpoint, YourPay, Paypal, WorldPay, BluePay, Protx</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>AVS Support</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Free Sub-domain</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Free Email Support</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Nightly Data Backup</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Online Help</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Browser Based Interface</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Free Disk Space</td><td align=center>5MB</td><td align=center>50MB</td><td align=center>100MB</td><td align=center>250MB</td><td align=center>500MB</td><td align=center>1GIG</td></tr>
<tr><td>Free Bandwidth</td><td align=center>.5 gig</td><td align=center>1 gig</td><td align=center>2 gig</td><td align=center>4 gig</td><td align=center>6 gig</td><td align=center>8 gig</td></tr>
<tr><td>CVV2 Card Code Verification</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Overall Meta Tags</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Free Top Level Domain
<BR>.com, .org, .us, .net, .biz or .info</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Catch-all Email Address</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Unique Meta Tags</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>

<tr bgcolor=DDDDDD><td width="50%"><B>Marketing Tools</b></td><td width="10%" align=center><B>BASIC</b></td><td width="10%" align=center><B>BRONZE</b></td><td width="10%" align=center><B>SILVER</b></td><td width="10%" align=center><B>GOLD</b></td><td width="10%" align=center><B>PLAT</b></td><td width="10%" align=center><B>UNLIM</b></td></tr>
<tr><td>Search Engine Registration and Tips</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Store Statistics</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Product Specials</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Discount and Free Promotions</td><td align=center>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Percent Off and Dollar Off Digital Coupons</td><td align=center>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Custom Mail Merge</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Banners</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Opt in Newsletter</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Affiliate Program</td><td align=center>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Rewards Program</td><td>&nbsp;</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Electronic Gift Certificates</td><td>&nbsp;</td><td>&nbsp;</td><td align=center>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Quantity Discounts</td><td align=center>&nbsp;</td><td align=center>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>
<tr><td>Froogle Integration</td><td>&nbsp;</td><td align=center>&nbsp;</td><td>&nbsp;</td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td><td align=center><img src=images/checkbox.gif border=0></td></tr>

</table>
<!--#include file="footer.asp"-->
