<!--#include file="Global_Settings.asp"-->
<!--#include file="pagedesign.asp"-->

<% 

' IF CALLING FROM AFFILIATES' PAGES, USE AFFILIATES_SESSION.ASP
' FOR SESSION MANAGEMENT
RUN_FROM_AFFILIATES = FALSE
	Session("AFFILIATE_SESSION")="FALSE"
	%><!--#include file="include\sub.asp"--><%
	

aff_id = request.form("AFF_DET_CODE")
start_date = cdate(request.form("AFF_DET_SDATE"))
end_date = cdate(request.form("AFF_DET_EDATE"))
sql_sel = "select * from store_affiliates where affiliate_id="&aff_id&" and store_id="&store_id
rs_store.open sql_sel, conn_store, 1, 1
	aff_code = rs_store("CODE")
	aff_cname = rs_store("Contact_name")
	aff_email = rs_store("Email")
	aff_url = rs_store("Url")
rs_store.close

sFormAction = "Affiliates_Reports.asp"
sTitle = "Affiliate Click and Order Details - "&aff_code
sFullTitle = "Marketing > <a href=affiliates_manager.asp class=white>Affiliates</a> > <a href=affiliates_reports.asp class=white>Reports</a> > Click and Order Details - "&aff_code
thisRedirect = "affiliates_details.asp"
sMenu = "marketing"
createHead thisRedirect

%>
 

		<TR bgcolor='#D4DEE5'><td width='100%' colspan='3' height='13'><table width='100%' border='0' cellspacing='1' cellpadding=2 class='list'>
				

						<tr bgcolor='#FFFFFF'>
							<td width="1%" nowrap>Contact</td>
							<td width="99%"><b><%= aff_cname %></b></td>
						</tr>
						
						<tr bgcolor='#FFFFFF'>
							<td width="1%" nowrap>Login</td>
							<td width="99%"><b><%= aff_code %></b></td>
						</tr>
		
						<tr bgcolor='#FFFFFF'>
							<td width="1%" nowrap>Email</td>
							<td width="99%"><b><a class="link" href="mailto:<%= aff_email %>"><%= aff_email %></a></b></td>
						</tr>
		
						<tr bgcolor='#FFFFFF'>
							<td width="1%" nowrap>URL</td>
							<td width="99%"><b><a class="link" href="<%= aff_url %>" target="_blank"><%= aff_url %></a></b></td>
						</tr>

					<tr bgcolor='#FFFFFF'>
						<td width="1%" nowrap>Period</td>
						<td width="99%"><b><%= start_date %> - <%= end_date %></b></td>
					</tr>
				</table>
			</td>
		</tr>

		<tr bgcolor='#FFFFFF'>
			<td width="100%" colspan="3" height="13" align="center"><b><br>Clicks<br>&nbsp;</b></td>
		</tr>

	<TR bgcolor='#D4DEE5'><td width='100%' colspan='3' height='13'><table width='100%' border='0' cellspacing='1' cellpadding=2 class='list'>
					<tr align='center' bgcolor='#0069B2' class='white'>
						<td align="center"><font class=white><b>Date/Time</b></font></td>
						<td align="center"><font class=white><b>Refer</b></font></td>
						<td align="center"><font class=white><b>Client IP</b></font></td>
						<td align="center"><font class=white><b>User Agent</b></font></td>
					</tr>
					<%' SELECTING AND DISPLAYING CLICKS GENERATED BY THE AFFILIATE %>
					<% sql_clicks = "select sys_created,store_id,referer,useragent,clientip,came_from from affiliate_click_report where CAME_FROM='"&aff_code&"' and Sys_Created>='"&start_date&"' and Sys_Created<'"&end_date&"' and store_id="&store_id&" order by Sys_Created" %>

					<% rs_store.open sql_clicks, conn_store, 1, 1 %>
					<% crow=0 %>
					<% do while not rs_store.eof %>
						<tr
						<% if crow mod 2 = 1 then %>
							bgcolor="#DDDDDD"
						<% else  %>
                                                        bgcolor="#FFFFFF"
                                                <% End If %>
						>
							<td><%= rs_store("Sys_Created") %>&nbsp;</td>
							<td><a href=<%= rs_store("Referer") %>><%= left(rs_store("Referer"),50) %></a>&nbsp;</td>
							<td><%= rs_store("ClientIP") %>&nbsp;</td>
							<td><%= rs_store("UserAgent") %>&nbsp;</td>
						</tr>
						<% crow = crow+1 %>
						<% rs_store.movenext %>
					<% loop %>
					<% rs_store.close %>
				</table>
			</td>
		</tr>

		<tr bgcolor='#FFFFFF'>
			<td width="100%" colspan="3" height="13" align="center"><b><br>Orders<br>&nbsp;</b></td>
		</tr>

		<TR bgcolor='#D4DEE5'><td width='100%' colspan='3' height='13'><table width='100%' border='0' cellspacing='1' cellpadding=2 class='list'>
					<tr align='center' bgcolor='#0069B2' class='white'>
						<td align="center"><font class=white><b>Date/Time</b></font></td>
						<td align="center"><font class=white><b>Order</b></font></td>
						<td align="center"><font class=white><b>Verified</b></font></td>
						<td align="center"><font class=white><b>Shipping Method</b></font></td>
						<td align="center"><font class=white><b>Payment Method</b></font></td>
						<td align="center"><font class=white><b>Grand Total</b></font></td>
					</tr>
					<%' SELECTING AND DISPLAYING ORDERS GENERATED BY THE AFFILIATE %>
					<% sql_orders = "select SP.Sys_Created, SP.OID, SP.verified, SP.Grand_Total, SP.Shipping_method_name, SP.Payment_Method from store_purchases SP where SP.verified=1 and SP.CAME_FROM='"&aff_code&"' and SP.Sys_Created>='"&start_date&"' and SP.Sys_Created<'"&end_date&"' and SP.store_id="&store_id&" order by SP.Sys_Created" %>

					<% rs_store.open sql_orders, conn_store, 1, 1 %>
					<% crow=0 %>
					<% do while not rs_store.eof %>
						<tr
						<% if crow mod 2 = 1 then %>
							bgcolor="#DDDDDD"
						<% else  %>
                                                        bgcolor="#FFFFFF"
                                                <% End If %>
						>
							<td><%= rs_store("Sys_Created") %></td>
							<td align="center"><%= rs_store("OID") %></td>
							<td align="center">
							<% If cint(rs_store("verified"))=0 then %>
								No
							<% Else %>
								Yes
							<% End If %>
							</td>
							<td><%= rs_store("Shipping_method_name") %></td>
							<td><%= rs_store("Payment_Method") %></td>
							<td align="center"><b><%= formatcurrency(rs_store("Grand_Total")) %></b></td>
						</tr>
						<% crow = crow+1 %>
						<% rs_store.movenext %>
					<% loop %>
					<% rs_store.close %>
				</table>
			</td>
		</tr>
       <% createFoot thisRedirect, 0%>
