<%

If Auth_Capture then
	x_type = "04"
else
	x_type = "05"
end if

sql_real_time = "exec wsp_real_time_property "&Store_Id&","&Real_Time_Processor&";"
rs_Store.open sql_real_time,conn_store,1,1

rs_Store.MoveFirst
Do While Not Rs_Store.EOF
	select case Rs_store("Property")
		case "Propay_username"
			Propay_username = decrypt(rs_store("Value"))
	end select
	Rs_store.MoveNext
Loop
Rs_store.Close

'Propay_certStr ="EasystorecreatorTestCertStraaa"
Propay_certStr = "P32Takq2541MapqPdofaeWvC7grdSA"

rs_store.open "select * from store_customers where record_type=0 and cid="&cid, conn_store, 1, 1
If not rs_Store.eof then
	billTo_firstName=rs_Store("First_name")
	billTo_lastName=rs_Store("Last_name")
	billTo_street1=rs_Store("Address1")
	billTo_city=rs_Store("City")
	billTo_state=rs_Store("State")
	billTo_postalCode=rs_Store("zip")
	billTo_country=rs_Store("Country")
	billTo_phoneNumber=rs_Store("Phone")
	billTo_email=rs_Store("email")
	amount = formatnumber((GGrand_Total * 100),0,0,0,0)
End If
rs_store.close


       'Dim XmlStr
			  Dim XMLRequest
        XMLRequest = "<?xml version='1.0'?>"
        XMLRequest = XMLRequest & "<!DOCTYPE Request.dtd> "
        XMLRequest = XMLRequest & "<XMLRequest> "
        XMLRequest = XMLRequest & "<username>"+ Propay_username +"</username> "
        XMLRequest = XMLRequest & "<certStr>"+ Propay_certStr +"</certStr> "
        XMLRequest = XMLRequest & "<class>palm</class> "
        XMLRequest = XMLRequest & "<XMLTrans> "	 
        XMLRequest = XMLRequest & "<transType>"&x_type&"</transType> "
        XMLRequest = XMLRequest & "<amount>"& amount &"</amount> "
        XMLRequest = XMLRequest & "<addr>"& billTo_street1 &", "& billTo_city &", "& billTo_state &"</addr> "
	      XMLRequest = XMLRequest & "<zip>"& billTo_postalCode &"</zip> "
        XMLRequest = XMLRequest & "<sourceEmail>"& Propay_username &"</sourceEmail> "
        XMLRequest = XMLRequest & "<ccNum>"+ CardNumber +"</ccNum> "
        XMLRequest = XMLRequest & "<expDate>"&Request.Form("mm")&Request.Form("yy")&"</expDate> "
        if Use_CVV2 then
					XMLRequest = XMLRequest &	"<CVV2>"+Card_Code+"</CVV2>"
				end if
        XMLRequest = XMLRequest & "<invNum>" + cstr(Oid) + "</invNum> "
        XMLRequest = XMLRequest & "</XMLTrans> "
        XMLRequest = XMLRequest & "</XMLRequest> "
        
    ' response.write "XMLRequest -" &XMLRequest

		Set objWinHttp = Server.CreateObject("WinHttp.WinHttpRequest.5.1") 

		'Test URL
		'URL = "http://devtst.propay.com/xml/xml.exe/process"
		
		'Production URL
		URL = "https://epay.propay.com/xml/xml.exe/process"



  objWinHttp.open "PUT", "https://epay.propay.com/xml/xml.exe/process", False
'  objWinHttp.setRequestHeader "Content-Type","application/x-www-form-urlencoded"

    Call objWinHttp.send(XMLRequest)

		PropayResponse = objWinHttp.ResponseText		
		Response.Write  PropayResponse 
'		Response.end
%>

		<br>
		<br>

<%

		Set objXML = Server.CreateObject("Microsoft.XMLDOM")		
		objXML.async="false"
		objXML.loadXML(objWinHttp.ResponseText)

		If objXML.parseError.errorCode <> 0 Then
			' handle the error
		End If

		Set objLst = objXML.getElementsByTagName("*")

		For i = 0 to objLst.length-1

			If objLst.item(i).nodeName = "resp" Then
				StrMsg = objLst.item(i).text
			End If

			If objLst.item(i).nodeName = "status" Then
				Status = objLst.item(i).text
			End If

' Transaction number generated by Propay

			If objLst.item(i).nodeName = "transNum" Then
				transNum = objLst.item(i).text
			End If

			If objLst.item(i).nodeName = "authCode" Then
				authCode = objLst.item(i).text
			End If
			
			If objLst.item(i).nodeName = "CVV2Resp" Then
				cvCode = objLst.item(i).text
			End If
			
			If objLst.item(i).nodeName = "AVS" Then
				avsCode = objLst.item(i).text
			End If

		Next

if Status="00" then

		AuthNumber = authNumber
		avs_result	= avsCode
		Verified_Ref =  transNum
		card_verif = cvCode
	

else ' REJECT or ERROR

select case Status
  case "20"
    StrMsg = "Invalid username"
  case "21"
    StrMsg = "Invalid transType"
  case "24"
    StrMsg = "Invalid sourceEmail"
  case "32"
    StrMsg = "Invalid billZip"
  case "44"
    StrMsg = "Invalid amount"
  case "47"
    StrMsg = "Invalid accntNum"
  case "48"
    StrMsg = "Invalid ccNum"
  case "49"
    StrMsg = "Invalid expDate"
  case "50"
    StrMsg = "Invalid cvv2"
  case "57"
    StrMsg = "Cannot settle transaction because it already expired"
  case "58"
    StrMsg = "Credit card declined"
  case "59"
    StrMsg = "User not authenticated"
  case "60"
    StrMsg = "Credit card authorization timed out; retry at a later time"
  case "61"
    StrMsg = "Amount exceeds single transaction limit"
  case "62"
    StrMsg = "Amount exceeds monthly volume limit"
  case "63"
    StrMsg = "Insufficient funds in account"
  case "64"
    StrMsg = "Over credit card use limit"
  case "65"
    StrMsg = "Miscellaneous error"
  case "67"
    StrMsg = "Unauthorized service requested"
  case "69"
    StrMsg = "Duplicate invoice number"
end select

reasonCode = StrMsg
fn_purchase_decline oid,"The transaction was rejected by the payment processor:<BR>"&reasonCode

end if

%>
