<!--#include virtual="common/connection.asp"-->

<%

' IF CALLING FROM AFFILIATES' PAGES, USE AFFILIATES_SESSION.ASP
' FOR SESSION MANAGEMENT
RUN_FROM_AFFILIATES = TRUE


aff_id = Session("AFFILIATE_AFFILIATE_ID")

start_date = cdate(request.form("AFF_DET_SDATE"))
end_date = cdate(request.form("AFF_DET_EDATE"))
sql_sel = "select * from store_affiliates where affiliate_id="&aff_id&" and store_id="&Session("AFFILIATE_STORE_ID")
rs_store.open sql_sel, conn_store, 1, 1
	aff_code = rs_store("CODE")
	aff_cname = rs_store("Contact_name")
	aff_email = rs_store("Email")
	aff_url = rs_store("Url")
rs_store.close

if Session("AFFILIATE_SESSION")="TRUE" then
	%><!--#include file="affiliates_session.asp"--><%
else
	Response.Redirect "affiliates_login.asp"

end if
%>
 
<html>

<head>
	<meta name="Pragma" content="no-cache">
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
	<title>Easystorecreator E-Commerce Manager</title>
</head>

<body>

<!--#include file="affiliates_header.asp"-->

<form method="POST" action="Affiliates_Reports.asp">

	<table border="1" width="100%" height="1" cellpadding="0" cellspacing="0" bordercolor="000066">
		<tr> 
			<td width="100%" bgcolor="#003399" height="19"><font color="#FFFFFF"><b>&nbsp;</b><font size="2" face="Arial"><b>Affiliate Clicks and Order Details</b></font></font></td>
		</tr>

		<tr bgcolor="#CBFA85">
			<td width="100%" colspan="3" height="13">
				<table border="0" width="100%" height="1" cellspacing="2" cellpadding="2">

					<tr>
						<td width="1%" nowrap><font face="Arial" size="2">Period</font></td>
						<td width="99%"><font face="Arial" size="2"><b><%= start_date %> - <%= end_date %></b></font></td>
					</tr>
				</table>
			</td>
		</tr>

		<tr>
			<td width="100%" colspan="3" height="13" align="center"><font face="Arial" size="2"><b><br>Clicks<br>&nbsp;</b></font></td>
		</tr>

	<tr>
		<td width="100%" colspan="3" height="13">
				<table border="1" width="100%" height="1" cellspacing="2" cellpadding="2">
					<tr>
						<td align="center"><font face="Arial" size="2"><b>Date/Time</b></font></td>
						<td align="center"><font face="Arial" size="2"><b>Refer</b></font></td>
						<td align="center"><font face="Arial" size="2"><b>Client IP</b></font></td>
						<td align="center"><font face="Arial" size="2"><b>User Agent</b></font></td>
					</tr>
					<%' SELECTING AND DISPLAYING CLICKS GENERATED BY THE AFFILIATE %>
					<% sql_clicks = "select * from store_shoppers where CAME_FROM='"&aff_code&"' and Sys_Created>=#"&start_date&"# and Sys_Created<#"&end_date&"# and store_id="&store_id&" order by Sys_Created" %>
					<% if Store_Database="Ms_Sql" then %>
						<% sql_clicks=replace(sql_clicks,"#","'") %>

					<% end if %>
					<% rs_store.open sql_clicks, conn_store, 1, 1 %>
					<% crow=0 %>
					<% do while not rs_store.eof %>
						<tr
						<% if crow mod 2 = 1 then %>
							bgcolor="#DDDDDD"
						<% End If %>
						>
							<td><font face="Arial" size="2"><%= rs_store("Sys_Created") %>&nbsp;</font></td>
							<td><font face="Arial" size="2"><a href=<%= rs_store("Referer") %>><%= left(rs_store("Referer"),50) %></a>&nbsp;</font></td>
							<td><font face="Arial" size="2"><%= rs_store("ClientIP") %>&nbsp;</font></td>
							<td><font face="Arial" size="2"><%= rs_store("UserAgent") %>&nbsp;</font></td>
						</tr>
						<% crow = crow+1 %>
						<% rs_store.movenext %>
					<% loop %>
					<% rs_store.close %>
				</table>
			</td>
		</tr>

		<tr>
			<td width="100%" colspan="3" height="13" align="center"><font face="Arial" size="2"><b><br>Orders<br>&nbsp;</b></font></td>
		</tr>

		<tr>
		<td width="100%" colspan="3" height="13">
				<table border="1" width="100%" height="1" cellspacing="2" cellpadding="2">
					<tr>
						<td align="center"><font face="Arial" size="2"><b>Date/Time</b></font></td>
						<td align="center"><font face="Arial" size="2"><b>Order</b></font></td>
						<td align="center"><font face="Arial" size="2"><b>Verified</b></font></td>
						<td align="center"><font face="Arial" size="2"><b>Shipping Method</b></font></td>
						<td align="center"><font face="Arial" size="2"><b>Payment Method</b></font></td>
						<td align="center"><font face="Arial" size="2"><b>Total</b></font></td>
					</tr>
					<%' SELECTING AND DISPLAYING ORDERS GENERATED BY THE AFFILIATE %>
					<% sql_orders = "select SP.Sys_Created, SP.OID, SP.verified, SP.Total, SP.Shipping_method_name, SP.Payment_Method from store_purchases SP where SP.verified=1 and SP.CAME_FROM='"&aff_code&"' and SP.Sys_Created>=#"&start_date&"# and SP.Sys_Created<#"&end_date&"# and SP.store_id="&store_id&" order by SP.Sys_Created" %>
					<% if Store_Database="Ms_Sql" then %>
						<% sql_orders =replace(sql_orders,"#","'") %>

					<% end if %>
					<% rs_store.open sql_orders, conn_store, 1, 1 %>
					<% crow=0 %>
					<% do while not rs_store.eof %>
						<tr
						<% if crow mod 2 = 1 then %>
							bgcolor="#DDDDDD"
						<% End If %>
						>
							<td><font face="Arial" size="2"><%= rs_store("Sys_Created") %></font></td>
							<td align="center"><font face="Arial" size="2"><%= rs_store("OID") %></font></td>
							<td align="center"><font face="Arial" size="2">
							<% If cint(rs_store("verified"))=0 then %>
								No
							<% Else %>
								Yes
							<% End If %>
							</font></td>
							<td><font face="Arial" size="2"><%= rs_store("Shipping_method_name") %></font></td>
							<td><font face="Arial" size="2"><%= rs_store("Payment_Method") %></font></td>
							<td align="center"><font face="Arial" size="2"><b><%= Session("AFFILIATE_CURRENCY") %><%= formatnumber(rs_store("Total")) %></b></font></td>
						</tr>
						<% crow = crow+1 %>
						<% rs_store.movenext %>
					<% loop %>
					<% rs_store.close %>
				</table>
			</td>
		</tr>
	</table>

</form>

</body>
</html>
