<%' ================================================================ %>
<%' WebStores 2000 - Version 5.0                                     %>
<%' (c) WebCortex Inc                                                %>
<%' ================================================================ %>
<%' FILE NAME   : AFFILIATES/INDEX.ASP                               %>
<%' DESCRIPTION : AFFILIATES MAIN PAGE, AFFFILIATES_SESSION.ASP      %>
<%'               FILE WILL REDIRECT AFFILIATE TO THE CORESPUNDING   %>
<%'               PAGE                                               %>
<%' ================================================================ %>
<%' THE FILE IS ACCESSING TABLES:                                    %>
<%' ---------------------------------------------------------------- %>
<%' THE FILE IS REFFERED / INCLUDED BY FILES:                        %>
<%' ================================================================ %>

<% Session("AFFILIATE_SESSION")="FALSE" %>
<!--#include file="affiliates_session.asp"-->