<%

sInstructions="The store information will be used on your contact us page to allow customers to contact you. Much of this information is not required but customers are more comfortable purchasing from stores which prominently display their address and phone number."
if instr(Shipping_Classes)>0 then
   sInstructions=sInstructions&"This information is also used as the default location from which your store shipments will be originating.You have selected to use realtime shipping so please ensure that the information below is correct to ensure accurate realtime quotes."
end if
sFlashHelp="company/company.htm"
sMediaHelp="company/company.wmv"
sZipHelp="company/company.zip"
sTextHelp="company/settings.doc"

objHelpDict.Add "address line 1","First line of address information.  All address information is used in invoices and the contact us page."
objHelpDict.Add "address line 2","Second line of address information."
objHelpDict.Add "city","Name of city where store resides."
objHelpDict.Add "company name","Name of the company which owns your store.  Used in invoices."
objHelpDict.Add "country","Name of country where store resides."
objHelpDict.Add "currency","Symbol to be used for prices throughout store.  If you wish to process real-time transactions in this currency please ensure that your default currency is setup correctly with your processor."
objHelpDict.Add "description","Description of your store for use in search engines to both index and show your site to potential searchers and customers.  This description will be used on all pages of your site."
objHelpDict.Add "email","Email address for customers to use."
objHelpDict.Add "fax","Fax number customers should use for contacting store."
objHelpDict.Add "invoice text","Text to be added to the bottom of all invoices."
objHelpDict.Add "keywords","Words which search engines will index your site on.  Do not use the same keywords more than 4 times but use important keywords in different forms. Separate keyword phrases with commas."
objHelpDict.Add "phone","Phone number customers should use for contacting store."
objHelpDict.Add "store name","Name of your store.  Used in default logo creation, title bar and invoices."
objHelpDict.Add "title","Title of your store pages.  Some search engines use this to index your site or to show to shoppers."
objHelpDict.Add "zip code","Postal or zipcode where store resides."
objHelpDict.Add "allow cookies","Allows shoppers the option of saving their login and password  information for future visits."
objHelpDict.Add "capture statistics","Turn on statistics gathering for your site.  Please note this will slow down your store slightly."
objHelpDict.Add "cart_thumbnails","Show small image for each item in shopping cart and invoice view."
objHelpDict.Add "content_width","The width of the center area of the header/footer."
objHelpDict.Add "continue_shopping","By default the continue shopping link will return the shopper to their previous browsing page.  To override this behavior enter the full address of the page where the continue shopping button should redirect the shopper."
objHelpDict.Add "gift message","Allow customer to enter a gift message to be included with their order."
objHelpDict.Add "gift wrapping","Give shoppers the option of having their purchases gift wrapped before being sent."
objHelpDict.Add "gift wrapping surcharge","Extra charge to add if shoppers selects to have their purchase gift wrapped."
objHelpDict.Add "hide_retail","Hide retail price in shopping cart"
objHelpDict.Add "ip tracking","Allow the store to use ip tracking in addition to cookie tracking so that customers without cookies can still shop."
objHelpDict.Add "members only","Do not require shoppers to register before purchasing items.  If unchecked all shoppers will be required to register by creating a login and password before being allowed to checkout."
objHelpDict.Add "no login","Skip the login page at checkout and just prompt shopper for information.  If you check this box you should also check express checkout otherwise shoppers will be asked for their username and password which they will not be able to enter on their next visi"
objHelpDict.Add "one click shopping","Allows shoppers the option of saving their shipping preferences for future visits."
objHelpDict.Add "public store","Allows any shopper to browse  your store without registering first."
objHelpDict.Add "show_residential","Show residential checkbox on registration screen to indicate residential address."
objHelpDict.Add "show_savecart","Include buttons to save and retrieve shopping cart on view cart page."
objHelpDict.Add "show_special_offers","Show special offers checkbox on registration screen."
objHelpDict.Add "show_tax_exempt","Show tax exempt checkbox on register screen."
objHelpDict.Add "when adding","Allow shopper to switch between showing and hiding shopping cart when adding new items."
objHelpDict.Add "minimum_amount","Minimum amount of order to checkout cart ."
%>