<%
sQuestion_Path = "inventory/add_item.htm"

objHelpDict.Add "accessories","Configure accessories for this item.  Accessories are linked to the item and offered as a purchase along with the item."
objHelpDict.Add "add new item","Add a new inventory item."
objHelpDict.Add "additional departments","Additional departments which item belongs to.  Use the CTRL key to select multiple items."
objHelpDict.Add "attributes","Configure attributes for this item.  Attributes are a way to modify items, attributes can have different prices ie XL shirts could be extra."
objHelpDict.Add "back to items","Return to listing of items."
objHelpDict.Add "configurations","Configure configurations for this item.  "
objHelpDict.Add "control #","Do not allow this item to be sold if quantity is equal to or below this number and quantity control is enabled."
objHelpDict.Add "cust price","Enable customer to set their own price for this item."
objHelpDict.Add "custom link","Override default item url and input a new item url to direct shoppers to when clicking on the item from the cart."
objHelpDict.Add "dates","Date range for special."
objHelpDict.Add "extended field 1","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "extended field 2","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "extended field 3","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "extended field 4","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "extended field 5","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "filename","Name of file to be downloaded upon order verification. To be used when item is a software file, image or otherwise downloadable item."
objHelpDict.Add "fractional","Allow shopper to purchase less than a whole item."
objHelpDict.Add "handling","Special handling fee to add on for shipping this item."
objHelpDict.Add "height","Height of item."
objHelpDict.Add "hide price","Do not show item price on any pages.  Since price is not shown item also cannot be ordered."
objHelpDict.Add "hide stock","Hide the number of items in stock for this item.  To be used if you dont want the customer to know how many there are."
objHelpDict.Add "homepage","Include this item on the stores homepage.  This should usually be reserved for sale or featured items, if your homepage has to many items they are no longer  special."
objHelpDict.Add "item remarks","Special notes to be displayed only to admin."
objHelpDict.Add "item_pin","Deliver electronic pin upon purchase."
objHelpDict.Add "large description","Description of item for use on item detail page."
objHelpDict.Add "large image","Large image for use on item detail page."
objHelpDict.Add "length","Length of item."
objHelpDict.Add "item_filename","The name of the html page that this item will be displayed on.  Cannot contain any special characters, only letters, numbers, dash and underscore."
objHelpDict.Add "meta_description","Description which search engines will use to index and show this item to potential searchers and customers."
objHelpDict.Add "meta_keywords","Words which search engines will index this item on."
objHelpDict.Add "meta_title","Title used by search engines for listing your site."
objHelpDict.Add "min quantity","Minimum quantity to allow a shopper to order."
objHelpDict.Add "name","Name of inventory item.  This is the name shown to the shopper."
objHelpDict.Add "pagename","The name of the file to be used when displaying this item.  Should be similiar to the name of the item, but cannot contain special characters."
objHelpDict.Add "price matrix","For use when set price by # of items is enabled.  This allows you to setup discounts such as buy 2 for 4.95 each buy 4 or more for 4.50"
objHelpDict.Add "qty control","Do not allow this item to be sold if quantity goes below the quantity control number."
objHelpDict.Add "qty discount","Enable price matrix so that shoppers can recieve discounts for ordering multiple items."
objHelpDict.Add "recurring_days","Number of days between recurring charges."
objHelpDict.Add "recurring_fee","The recurring price of this item.  Note this fee will not effect specials, promotions, shipping or coupons."
objHelpDict.Add "retail price","Price of item in your store before any discounts, coupons, specials or quantity discounts."
objHelpDict.Add "shipfrom","The location that this item will ship from."
objHelpDict.Add "shipping fee","Shipping Fee for this item. For use when shipping class is set to Per Item Shipping."
objHelpDict.Add "short description","Description of item for use on department browse page."
objHelpDict.Add "show on homepage","Show this item on stores homepage."
objHelpDict.Add "sku","Stock Keeping Unit for this inventory item."
objHelpDict.Add "small image","Small image for use on department browse page."
objHelpDict.Add "special description","Description to show for this special."
objHelpDict.Add "special price","Percentage of discount for this item between start and end date."
objHelpDict.Add "stock","Current number of items in stock."
objHelpDict.Add "store department","Primary department which item belongs to."
objHelpDict.Add "taxable","Enable tax calculation on this item.  Most items are taxable please view your state laws for information."
objHelpDict.Add "user field","Name of optional field and whether it is enabled or not."
objHelpDict.Add "view order","Numerical value to order items by, if you wish to order items alphabetically keep all items set to 0.  You may use fractional or negative numbers if needed.  Smaller numbers are shown first."
objHelpDict.Add "visible","Show item in store.  If not visible shoppers will not be able to purchase."
objHelpDict.Add "waive shipping","If checked the system will disregard this item when calculating shipping. ie its weight or price will not affect shipping charges."
objHelpDict.Add "weight","Weight of item.  For use in determining total shipping weight.  Units doesnt matter but should be consistent throughout.  "
objHelpDict.Add "wholesale price","Wholesale price of item to use in determining profit margin."
objHelpDict.Add "width","Width of item."

 %>