<%

objHelpDict.Add "additional departments","Additional departments which item belongs to.  Use the CTRL key to select multiple items."
objHelpDict.Add "brand","The brand name of the product."
objHelpDict.Add "condition","The condition of the product,ie new, used or refurbished."
objHelpDict.Add "control #","Do not allow this item to be sold if quantity is equal to or below this number and quantity control is enabled."
objHelpDict.Add "custom pricing","Enable customer to set their own price for this item."
objHelpDict.Add "date","Date range that special price is available for."
objHelpDict.Add "dates","Date range that special price is available for."
objHelpDict.Add "department","Primary department which item belongs to."
objHelpDict.Add "extended field 1","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "extended field 2","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "extended field 3","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "extended field 4","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "extended field 5","Can be used to hold any extra information for display to your customers"
objHelpDict.Add "filename","Name of file to be downloaded upon order verification. To be used when item is a software file, image or otherwise downloadable item."
objHelpDict.Add "fractional","Allow shopper to purchase less than a whole item."
objHelpDict.Add "handling","Special handling fee to add on for shipping this item."
objHelpDict.Add "hide price","Do not show item price on any pages.  Since price is not shown item also cannot be ordered."
objHelpDict.Add "home page","Include this item on the stores homepage.  This should usually be reserved for sale or featured items, if your homepage has to many items they are no longer  special."
objHelpDict.Add "item remarks","Special notes to be displayed only to admin."
objHelpDict.Add "item_pin","Deliver electronic pin upon purchase."
objHelpDict.Add "large description","Description of item for use on item detail page."
objHelpDict.Add "large image","Large image for use on item detail page."
objHelpDict.Add "meta_description","Description which search engines will use to index and show this item to potential searchers and customers."
objHelpDict.Add "meta_keywords","Words which search engines will index this item on."
objHelpDict.Add "meta_title","Title used by search engines for listing your site."
objHelpDict.Add "min quantity","Minimum quantity to allow a shopper to order."
objHelpDict.Add "product_type","The type of product, please see Google Base documentation for sample values."
objHelpDict.Add "qty control","Do not allow this item to be sold if quantity goes below the quantity control number."
objHelpDict.Add "qty discount","Enable price matrix so that shoppers can recieve discounts for ordering multiple items."
objHelpDict.Add "quantity","Current number of items in stock."
objHelpDict.Add "recurring_days","Number of days between recurring charges."
objHelpDict.Add "recurring_fee","The recurring price of this item.  Note this fee will not effect specials, promotions, shipping or coupons."
objHelpDict.Add "retail price","Price of item in your store before any discounts, coupons, specials or quantity discounts."
objHelpDict.Add "shipfrom","The location that this item will ship from."
objHelpDict.Add "shipping fee","Shipping Fee for this item. For use when shipping class is set to No Shipping."
objHelpDict.Add "short description","Description of item for use on department browse page."
objHelpDict.Add "small image","Small image for use on department browse page."
objHelpDict.Add "special price","Discount items to a certain percentage of their previous price for the specified dates."
objHelpDict.Add "stock","Current number of items in stock."
objHelpDict.Add "taxable","Enable tax calculation on this item.  Most items are taxable please view your state laws for information."
objHelpDict.Add "user field","Name of optional field and whether it is enabled or not."
objHelpDict.Add "visible","Show item in store.  If not visible shoppers will not be able to purchase."
objHelpDict.Add "waive shipping","If checked the system will disregard this item when calculating shipping. ie its weight or price will not affect shipping charges."
objHelpDict.Add "weight","Weight of item.  For use in determining total shipping weight.  Units doesnt matter but should be consistent throughout.  "
objHelpDict.Add "wholesale price","Wholesale price of item to use in determining profit margin."


 %>