<%

objHelpDict.Add "area border","Border size for Design Area"
objHelpDict.Add "area border color","Border Color for Design Area"
objHelpDict.Add "area design bg","Background for Design Area"
objHelpDict.Add "area height","Height for Design Area"
objHelpDict.Add "area width","Width for Design Area"
objHelpDict.Add "banner protocol","Protocol to be used for the link"
objHelpDict.Add "banner target","Target window where the link would be opened"
objHelpDict.Add "banner text","Text for the Banner link"
objHelpDict.Add "banner url","URL of the link (without the protocol) e.g. www.easystorecreator.com"
objHelpDict.Add "design area","Section of the store page design layout"
objHelpDict.Add "hr color","color of the Horizontal Rule"
objHelpDict.Add "html text","HTML content"
objHelpDict.Add "image alternate text","Tooltip text for the image"
objHelpDict.Add "image border","Border sIze for the image"
objHelpDict.Add "image hspace","Horizontal Space on left and right side of the image"
objHelpDict.Add "image path","Path of the image file to display for this object"
objHelpDict.Add "image vspace","Vertical Space above and below the image"
objHelpDict.Add "link protocol","Protocol to be used for the link"
objHelpDict.Add "link target","Target window where the link would be opened"
objHelpDict.Add "link text","Text for the link"
objHelpDict.Add "nav buttons active button color","Color of the Active Navigation button"
objHelpDict.Add "nav buttons bg","Background for Navigation buttons area"
objHelpDict.Add "nav buttons bold","Font Bold style of the Navigation button text"
objHelpDict.Add "nav buttons border color","Color of border of each Navigation button"
objHelpDict.Add "nav buttons border size","Size of border of each Navigation button"
objHelpDict.Add "nav buttons color","Color of each Navigation button"
objHelpDict.Add "nav buttons font","Font face of the Navigation button text"
objHelpDict.Add "nav buttons font size","Font size of the Navigation button text"
objHelpDict.Add "nav buttons height","Height of each Navigation button"
objHelpDict.Add "nav buttons italic","Font Italic style of the Navigation button text"
objHelpDict.Add "nav buttons position","Position of the Navigation buttons, either Vertical or Horizontal"
objHelpDict.Add "nav buttons spacing","Space between each Navigation button"
objHelpDict.Add "nav buttons text align","Alignment of Navigation button Text"
objHelpDict.Add "nav buttons text color","Color of the Navigation button text"
objHelpDict.Add "nav buttons width","Width of each Navigation button"
objHelpDict.Add "nav links bg color","Background Color of the Navigation links area"
objHelpDict.Add "nav links bold","Font Bold Style for Navigation link text"
objHelpDict.Add "nav links border bg color","Color of the border of the Navigation links area"
objHelpDict.Add "nav links border size","Size of the border of the Navigation links area"
objHelpDict.Add "nav links font","Font face of the Navigation link text"
objHelpDict.Add "nav links font size","Font size of the Navigation link text"
objHelpDict.Add "nav links hover color","Color of Navigation link text of a link that was moved over"
objHelpDict.Add "nav links italic","Font Italic Style for Navigation link text"
objHelpDict.Add "nav links position","Position of the Navigation Links, either Vertical or Horizontal"
objHelpDict.Add "nav links seperator","Character to be used as a seperator for the Navigation links"
objHelpDict.Add "nav links spacing","Space between each Nav link"
objHelpDict.Add "nav links text color","Color of Navigation link text"
objHelpDict.Add "nav links visited color","Color of a Navigation link text of a link that was previously visited"
objHelpDict.Add "object alignment","Alignment of the Object, leave blank for default value"
objHelpDict.Add "object height","Height of the Object, leave blank for default value"
objHelpDict.Add "object width","Width of the Object, leave blank for default value"
objHelpDict.Add "same line","Specify where to put the next object, on the same line as this object or on the next line."
objHelpDict.Add "space bg color","Background Color for the Space object"
objHelpDict.Add "space border color","Color of the border of Space object"
objHelpDict.Add "space border size","Size of the Border of Space object"
objHelpDict.Add "url","The URL of the link without the protocol, e.g www.easystorecreator.com"
objHelpDict.Add "vertical spacing","Vertical Space above and below the image"

 %>