<%

sQuestion_Path = "reports/customers.htm"

objHelpDict.Add "address line 1","The first line of the customers address."
objHelpDict.Add "address line 2","The second line of the customers address."
objHelpDict.Add "budget","Starting budget for this customer.  A budget implies a credit for the customer.  They will be able to use this credit when shopping to pay for their orders and the total will be removed from their available budget."
objHelpDict.Add "budget left","Amount remaining of budget for this customer.  When budget left equals zero the shopper no longer has a credit on their account and they cannot choose the charge my account option at checkout."
objHelpDict.Add "city","The customers city."
objHelpDict.Add "company","The customers company."
objHelpDict.Add "country","The customers country."
objHelpDict.Add "customer id","The unique number used throughout the database to identify this customer."
objHelpDict.Add "email","The customers email address."
objHelpDict.Add "express shopping","If checked, the customer has requested to save their shipping preferences for next time."
objHelpDict.Add "fax","The customers contact fax number."
objHelpDict.Add "first name","The first name of the customer."
objHelpDict.Add "in groups","Shopper belongs to the groups listed.  If you would like to add them to more groups go to the customer groups screen."
objHelpDict.Add "last name","The last name of the customer."
objHelpDict.Add "matching groups","Shopper belongs to the groups listed"
objHelpDict.Add "password","Password this customer will use to login to your store to purchase items, view past orders, modify information etc.  If the entry says express checkout the shopper did not create a login."
objHelpDict.Add "password confirm","Retype password to avoid typing errors."
objHelpDict.Add "phone","The customers contact phone number."
objHelpDict.Add "plus groups","Shopper was manually added to the groups listed"
objHelpDict.Add "promo emails","If checked, the customer has asked that you send them promotional emails from time to time."
objHelpDict.Add "protected access","Allow this customer access to store pages that have been marked as protected."
objHelpDict.Add "reward_left","Current rewards balance."
objHelpDict.Add "reward_total","Total amount customer has earned to use for rewards."
objHelpDict.Add "state","The customers state."
objHelpDict.Add "tax exempt","If checked, the customer will not be charged sales tax, regardless of the ship to zip code."
objHelpDict.Add "tax_id","The customers tax id for tax exempt purposes."
objHelpDict.Add "username","Username this customer will use to login to your store to purchase items, view past orders, modify information, etc.  If the entry says express checkout the shopper did not create a login."
objHelpDict.Add "zipcode","The customers zip or postal code."

 %>