<%

sFlashHelp="paymentprocessor/paymentprocessor.htm"
sMediaHelp="paymentprocessor/paymentprocessor.wmv"
sZipHelp="paymentprocessor/paymentprocessor.zip"
sInstructions="Please note that the card code and auth and deposit settings are only used for realtime processors.  The card code cannot be stored persistantly due to Visa/Mastercard regulations, it can only be sent directly to a payment gateway.  The authorization and deposit functionality is also only valid when using a real time processor.  If you have selected No Processor these values will be ignored."

objHelpDict.Add "account_id","Your Bluepay account id"
objHelpDict.Add "authorization and deposit","There are 2 main types of credit card transactions, authorization only and authorization with deposit.  You should check with your real-time processor to determine the method to use.  Most processors require you to ship within a certain time period of dep"
objHelpDict.Add "authorize and deposit","There are 2 main types of credit card transactions, authorization only and authorization with deposit.  You should check with your real-time processor to determine the method to use.  Most processors require you to ship within a certain time period of dep"
objHelpDict.Add "bmc_login","The BluePay merchant login number assigned to you."
objHelpDict.Add "config_file_name","The config file name given to you by PSI Gate"
objHelpDict.Add "cybersource_currency","The currency code to use for processing transactions."
objHelpDict.Add "cybersource_id","Your unique cybersource id for processing transactions."
objHelpDict.Add "epnaccount","The account number given to you by Electronic Transfer"
objHelpDict.Add "ioc_merchant_id","Bank of America Store Id"
objHelpDict.Add "m_id","Your stores unique Merchant id given by EftNet"
objHelpDict.Add "m_key","Your stores unique Merchant key given by EftNet"
objHelpDict.Add "mb_pay_currency","3 digit currency code of currency for transactions."
objHelpDict.Add "mb_pay_to_email","MoneyBookers email address where payments should be sent to."
objHelpDict.Add "merchant_echo_id","Echo merchant id, used for processing transactions."
objHelpDict.Add "merchant_echo_pin","Echo merchant pin, used for processing transaction."
objHelpDict.Add "merchantid","Your stores unique merchant id given to you by payment resource."
objHelpDict.Add "merchantkey","Your stores unique merchant key given by PRI."
objHelpDict.Add "merchantnumber","The unique merchant number given to you by internet secure to identify your transactions."
objHelpDict.Add "no processor","No real time processor is enabled for processing credit cards.  If you enable credit card payments and you select no processor the credit card numbers will be stored for your retrieval"
objHelpDict.Add "no real-time processor","Store has no relationship with a credit card processor.  Store either does not accept credit cards or processes them manually."
objHelpDict.Add "nochex_email","NoChex email address to credit payments to."
objHelpDict.Add "pay_currency","The digit currency code to use for Paypal payments."
objHelpDict.Add "pay_to","Paypal pay to email, required if paypal is enabled as a payment method."
objHelpDict.Add "paypal_pro_api_username","Paypal pro api username"
objHelpDict.Add "paypal_pro_password","Paypal pro password"
objHelpDict.Add "paytoid","The id given to your company by checksbynet"
objHelpDict.Add "pl_login","Payflow Link login, used for processing transactions"
objHelpDict.Add "pl_partner","Payflow Link partner, used for processing transactions"
objHelpDict.Add "processor settings","Each processor requires different settings to identify your store during transactions.  The processor should of given you instructions upon signing up.  You should ensure that each field for the selected processor is filled with the correct data or your t"
objHelpDict.Add "propay_certstr","Your propay certification string"
objHelpDict.Add "propay_username","Your propay username"
objHelpDict.Add "publisher-name","The unique name given to you by plugnpay to identify your transactions."
objHelpDict.Add "require card code","Card code is the 3 digit code on the back of your credit card.  Requiring this information can provide an additional level of security. Check with your realtime processor to determine how card code is used."
objHelpDict.Add "secret_key","Your Bluepay secret key"
objHelpDict.Add "seller_id","5 digit number given to you by 2Checkout which uniquely identifies your store"
objHelpDict.Add "storename","Storename given to you by Linkpoint when you signed up.  Usually this is a numeric value starting with 1 and followed by a series of 0s"
objHelpDict.Add "use 2checkout","Store will use 2Checkout to process transactions.  See link for more information or to signup."
objHelpDict.Add "use authorize.net ","Store uses authorize.net to process credit cards.  See link for more information or to signup."
objHelpDict.Add "use bluepay","Store will use BluePay to process transactions.  See link for more information or to signup."
objHelpDict.Add "use checksbynet","Enter your checksbynet id below to use the checksbynet system"
objHelpDict.Add "use cybersource","Store will use Cybersource to process transactions.  See link for more information or to signup."
objHelpDict.Add "use echo","Store uses echo to process credit cards."
objHelpDict.Add "use eft","Store will use EftNet.com for payment processing."
objHelpDict.Add "use electronic transfer","Store will use Electronic Transfer to process transactions."
objHelpDict.Add "use gcheckout","Store will use GoogleCheck as an optional. Please fill the following key and id."
objHelpDict.Add "use internet secure","Store uses internet secure to process credit cards."
objHelpDict.Add "use linkpoint","Store will use LinkPoint to process transactions.  See link for more information or to signup."
objHelpDict.Add "use moneybookers","Store will use MoneyBookers to process credit cards."
objHelpDict.Add "use nochex","Store will use NoChex to process credit cards."
objHelpDict.Add "use payflow link","Store will use Payflow Link to process transaction.  See link for information or to signup for an account."
objHelpDict.Add "use payflow pro","Store will use Payflow Pro to process transactions.  See link for more information or to signup."
objHelpDict.Add "use paypal","Store uses paypal to process credit cards in real-time.  See link to signup or get additional information."
objHelpDict.Add "use paypalpro","Use Paypal payments pro to process your transactions"
objHelpDict.Add "use pri","Store will use Payment Resources International for credit card processing."
objHelpDict.Add "use propay","Store will use Propay"
objHelpDict.Add "use protx","Store will use Protx to process credit cards."
objHelpDict.Add "use psi gate","Store will use PSI gate to process transactions.  See link for more information or to signup."
objHelpDict.Add "use worldpay","Store will use WorldPay to process transactions."
objHelpDict.Add "use xor","Use the XOR payment gateway for realtime processing"
objHelpDict.Add "use_echo","Store will use Echo to process transactions.  See link for information or to request an application."
objHelpDict.Add "use_pnp","Store uses plugnpay to process credit cards."
objHelpDict.Add "v_partner","Payflow Pro partner name, used for processing transactions."
objHelpDict.Add "v_password","Payflow Pro password, used for processing transactions."
objHelpDict.Add "v_user","Payflow Pro username, used for processing transactions."
objHelpDict.Add "v_vendor","Payflow Pro vendor name, used for processing transactions."
objHelpDict.Add "vendorcurrency","3 digit ISO currency code for currency to process transactions in."
objHelpDict.Add "vendorname","Unique name given to your by Protx for processing credit cards."
objHelpDict.Add "vendorpassword","Password used to login to Protx and send transactions"
objHelpDict.Add "worldpay_currency","3 digit currency code for default currency to use"
objHelpDict.Add "worldpay_instid","Your unique worldpay installation id number."
objHelpDict.Add "x_login","Authorize.Net login, used for processing transactions."
objHelpDict.Add "x_tran_key","Authorize.Net transactionkey, used for processing transactions."
objHelpDict.Add "xor_currency","Xor Currency code"
objHelpDict.Add "xor_password","Xor Password"
objHelpDict.Add "xor_terminalno","Xor Terminal No"
objHelpDict.Add "xor_user","Xor Username"
objHelpDict.Add "show_securelogo","Show secure site logo on credit card entry page." 

 %>