<%

sFlashHelp="shipping/shipping.htm"
sMediaHelp="shipping/shipping.wmv"
sZipHelp="shipping/shipping.zip"
sTextHelp="shipping/shipping-settings.doc"
sQuestion_Path = "general/shipping.htm"

objHelpDict.Add "handling_fee","Flat fee to be added to shipping method price."
objHelpDict.Add "handling_weight","Flat weight fee to be added to all shipments to cover weight of boxes and/or packing materials."
objHelpDict.Add "ship multi","Allow shoppers to specify separate ship to addresses for the different items in their shopping cart."
objHelpDict.Add "show shipping","Show Shipping options at the time of checkout"
objHelpDict.Add "canada login","Enter your Canada Post login"
objHelpDict.Add "conway login","Enter your Conway login"
objHelpDict.Add "conway password","Enter your Conway password"
objHelpDict.Add "dhl service","Select the DHL Service you would like to retrieve rates for."
objHelpDict.Add "fedex ground","Enable or disable the retrieval of Fedex Ground rates in addition to Express rates."
objHelpDict.Add "fedex pack","Select the method that will be to pack your Fedex Packages."
objHelpDict.Add "flat fee","Shoppers will be charged a flat fee for shipping regardless of total weight or total sale."
objHelpDict.Add "flat fee plus weight","Shoppers will be charged a flat fee for shipping regardless of weight plus a percentage of the total weight."
objHelpDict.Add "no shipping (per item only)","Shipping will be calculated on a per item basis with no general shipping charges."
objHelpDict.Add "percentage of total order","Shoppers will be charged a shipping fee equal to a percentage of the total order amount."
objHelpDict.Add "real shipping rates","Lookup rates from any combination of the shippers below.  Note: real time shipping rates take much longer to compute than any other method."
objHelpDict.Add "shipper name","The name of the company or person shipping."
objHelpDict.Add "shipping method details","Configure the details for the selected shipping method included countries to ship to and shipping prices."
objHelpDict.Add "total order matrix","Shoppers will be charged a shipping fee based on total order amount."
objHelpDict.Add "total weight matrix","Shoppers will be charged a shipping fee based on total order weight."
objHelpDict.Add "ups account number","The account number for your UPS account"
objHelpDict.Add "ups license","The access license given to you by UPS, see instructions for information on how to get UPS login."
objHelpDict.Add "ups pack","Select the method that will be to pack your UPS Packages."
objHelpDict.Add "ups password","The password given to you by UPS"
objHelpDict.Add "ups pickup","Select the method that will be used for picking up your UPS Packages."
objHelpDict.Add "ups username","The username given to you by UPS"
objHelpDict.Add "use airborne","Contact Airborne for realtime shipping rates"
objHelpDict.Add "use canada","Contact Canada Post for realtime shipping rates"
objHelpDict.Add "use conway","Contact Conway for realtime shipping rates"
objHelpDict.Add "use dhl","Contact DHL for realtime shipping rates."
objHelpDict.Add "use fedex","Contact Fedex for realtime shipping rates."
objHelpDict.Add "use ups","Contact UPS for realtime shipping rates"
objHelpDict.Add "use usps","Contact USPS for realtime shipping rates."
objHelpDict.Add "countries","Select the countries you wish to apply realtime shipping to.  Use the CTRL key to select multiple countries."
objHelpDict.Add "max_weight","The maximum weight per package when using realtime shipping.  If the weight of the cart exceeds the maximum it will be split into separate packages."
objHelpDict.Add "name","Comma separated list of the shipping method you do not wish to allow customers to choose."

 %>